x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  homeassistant:
    <<: *defaults
    image: lscr.io/linuxserver/homeassistant:2026.4.4@sha256:85d9a3cea7bfb86c4c993f64761bb68290d492dd8f6865a0f817b96bad4f6014
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
