services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.4.3@sha256:ae0800c81fea16bc1241ce03bddb9c6260566e90f58b09d3e5a629e4f68bdc0b
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: America/Los_Angeles
    volumes:
      - ./config:/config
      - ./etc/localtime:/etc/localtime:ro
      - ./run/dbus:/run/dbus:ro
