---
x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
services:
  jellyfin:
    <<: *defaults
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    image: lscr.io/linuxserver/jellyfin:10.11.10@sha256:c0ed73678fb4ca761e0d940a92e49b95352f7f241a9be79a2c575c0099288f46
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 7359:7359/udp
      - 1900:1900/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /mnt/media/anime/movies:/data/movies:ro
      - /mnt/media/anime/shows:/data/tvshows:ro
      - /mnt/media/movies:/data/movies:ro
      - /mnt/media/music:/data/music:ro
      - /mnt/media/shows:/data/tvshows:ro
