---
x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
services:
  jellyfin:
    <<: *defaults
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    image: lscr.io/linuxserver/jellyfin:10.11.9@sha256:155fb51c745d1a2c28c8b300612bc728a5dd06097bbc62b8b1c76d174eb20366
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 7359:7359/udp
      - 1900:1900/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /mnt/media:/media:ro
