---
x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"
services:
  jellyfin:
    <<: *defaults
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    image: lscr.io/linuxserver/jellyfin:10.11.11@sha256:4f6d8dfc53ec5a1ddf7a90e4338972d57d7b0adff6dc88b53184f8285d0b594f
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 7359:7359/udp
      - 1900:1900/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /mnt/media/anime/movies:/data/movies:ro
      - /mnt/media/anime/shows:/data/tvshows:ro
      - /mnt/media/movies:/data/movies:ro
      - /mnt/media/music:/data/music:ro
      - /mnt/media/shows:/data/tvshows:ro
