x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  read_only: true
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  mc:
    <<: *defaults
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    image: itzg/minecraft-server:2026.5.0-java25@sha256:fbbcfc47bc1239b57deb655162e950bd22c87df8034a2251d1f906eb2c8d3da4
    ports:
      - "25565:25565/tcp"
      - "24454:24454/udp"
    environment:
      UID: 1000
      GID: 1000
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "26.1"
      MEMORY: "12288M"
      MAX_PLAYERS: "2"
      USE_MEOWICE_FLAGS: "true"
      TZ: "America/Los_Angeles"
      DIFFICULTY: "3"
      SIMULATION_DISTANCE: "16"
      VIEW_DISTANCE: "16"
      ENABLE_WHITELIST: "true"
      WHITELIST: |-
        eyeofgrey
        vi6ann
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      LOG_TIMESTAMP: "true"
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOPAUSE: "TRUE"
    volumes:
      - "./data:/data"
