x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  read_only: true
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  uptime-kuma:
    <<: *defaults
    image: louislam/uptime-kuma:2.2.1@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
    user: 1000:1000
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
