x-defaults: &defaults
  restart: unless-stopped
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges:true
  read_only: true
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  uptime-kuma:
    <<: *defaults
    image: louislam/uptime-kuma:2.3.0@sha256:a8e5e69ce185d5425fcbf2ab14ddf808df5651fb2747a46a17cecf8ed5fd1af2
    user: 1000:1000
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
